### ISSUE TITLE
having an issue on windows with the smal fitter

### ISSUE THREAD

**Issue by elephantguy256** [benjiebob/SMALify#15]
I was trying to run the smal fitter on windows and I get this error from pickle.py

Traceback (most recent call last):
  File "smal_fitter/optimize_to_joints.py", line 147, in <module>
    main()
  File "smal_fitter/optimize_to_joints.py", line 89, in main
    model = SMALFitter(device, data, config.WINDOW_SIZE, config.SHAPE_FAMILY, use_unity_prior)
  File "C:\Users\Owner\Documents\GitHub\SMALify\smal_fitter\smal_fitter.py", line 46, in __init__
    smal_data = u.load()
  File "E:\Program Files\Python37\lib\pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "E:\Program Files\Python37\lib\pickle.py", line 1209, in load_string
    raise UnpicklingError("the STRING opcode argument must be quoted")
_pickle.UnpicklingError: the STRING opcode argument must be quoted

this is the error I am getting

**Comment by benjiebob** [comment]
Could this help: https://github.com/benjiebob/SMALify/issues/10

**Comment by benjiebob** [comment]
Closing due to inactivity.
