### ISSUE TITLE
Python 3.7 cPickle

### ISSUE THREAD

**Issue by monajalal** [benjiebob/SMALify#4]
For running the code in Anaconda Python 3.7,

```
##import cPickle as pickle
import pickle as cPickle
```

in the following file:
`
(base) mona@mona:~/research/3danimals/SMALify$ vi /home/mona/research/3danimals/SMALify/smal_model/smpl_webuser/serialization.py`

Otherwise, you will get this error:

```
(base) mona@mona:~/research/3danimals/SMALify$ python smal_fitter/optimize_to_joints.py

Bad key savefig.frameon in file /home/mona/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 421 ('savefig.frameon : True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.2/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.level in file /home/mona/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 472 ('verbose.level  : silent      # one of silent, helpful, debug, debug-annoying')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.2/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.fileo in file /home/mona/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 473 ('verbose.fileo  : sys.stdout  # a log filename, sys.stdout or sys.stderr')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.2/matplotlibrc.template
or from the matplotlib source distribution
In /home/mona/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/mona/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/mona/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /home/mona/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/mona/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/mona/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/mona/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/mona/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
Traceback (most recent call last):
  File "smal_fitter/optimize_to_joints.py", line 10, in <module>
    from smal_fitter import SMALFitter
  File "/home/mona/research/3danimals/SMALify/smal_fitter/smal_fitter.py", line 19, in <module>
    from smal_model.smal_torch import SMAL
  File "/home/mona/research/3danimals/SMALify/smal_model/smal_torch.py", line 15, in <module>
    from .smal_basics import align_smal_template_to_symmetry_axis, get_smal_template
  File "/home/mona/research/3danimals/SMALify/smal_model/smal_basics.py", line 4, in <module>
    from smal_model.smpl_webuser.serialization import load_model
  File "/home/mona/research/3danimals/SMALify/smal_model/smpl_webuser/serialization.py", line 26, in <module>
    import cPickle as pickle
ModuleNotFoundError: No module named 'cPickle'

```

**Comment by monajalal** [comment]
or actually better yet, just use `import pickle`

https://stackoverflow.com/a/49579373/2414957

**Comment by benjiebob** [comment]
https://github.com/benjiebob/SMALify/issues/6#issuecomment-702278462
